name: membership
version: 0.0.7
author: Dzenan Ridjanovic
description: Spirals of the membership application with one concept and several web components.
homepage: http://ondart.me/ui/index.md
dependencies:
  browser: any
  web_ui: any
